--liquibase formatted sql

create table position
(
    id         int generated by default as identity primary key ,
    position_name varchar (100),
    department varchar(100)

);

create table employee
(
    id int generated by default as identity primary key ,
    last_name varchar (100),
    age int check (age > 20),
    position_id int references position(id)
);

create table customer
(
   id int generated by default as identity primary key ,
   customer_name varchar (100),
   account varchar (100)
);

create table project
(
    id int generated by default as identity primary key ,
    project_name varchar(100),
    cost int,
    customer_id int references customer(id)
);

create table employee_project
(
    employee_id int REFERENCES Employee (id),
    project_id  int REFERENCES Project (id),
    PRIMARY KEY (employee_id, project_id)
);